// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAshPdf5VIkExRrRx4gkEf0BJUM5CPHKpQ',
    appId: '1:206805142346:web:f85d98871c449ebdddcfb3',
    messagingSenderId: '206805142346',
    projectId: 'sikcal-image',
    authDomain: 'sikcal-image.firebaseapp.com',
    storageBucket: 'sikcal-image.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoOj4K30gRhbZTmXcTNaMLLhZ1z23RGvg',
    appId: '1:206805142346:android:fa42c3a76665182bddcfb3',
    messagingSenderId: '206805142346',
    projectId: 'sikcal-image',
    storageBucket: 'sikcal-image.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC18QdlxjgBOTo9zY_C25T-w19_OFFbLv4',
    appId: '1:206805142346:ios:b7b49aed65491483ddcfb3',
    messagingSenderId: '206805142346',
    projectId: 'sikcal-image',
    storageBucket: 'sikcal-image.appspot.com',
    iosClientId: '206805142346-ob5ma0fei9kpp1uus180mktbfhi4tbct.apps.googleusercontent.com',
    iosBundleId: 'com.appgaebom.sikcal',
  );
}
